development:
  adapter: postgresql
  database: walo_dev
  username: postgres
  password: admin
  host: localhost

test:
  adapter: postgresql
  database: walo_test
  username: postgres
  password: admin
  host: localhost

production:
  adapter: postgresql
  database: walo_prod
  username: postgres
  password: admin